### PR TITLE
Updated JDBC driver, reference data set and Dockerfile

### PR DESCRIPTION
**Pull request by christianbader**
- Updated JDBC driver to newest version 2.2.0
- Updated reference data set in order to work with crate > v2.1
- Updated documentation regarding registering a Connector Server
- Fixed some issues in Dockerfile

### CODE REVIEW

**Comment by bowenwr** [comment]
Before we can merge, it has to pass integration tests. It looks like it's using my local user by default and failing authentication. `sudo su postgres` didn't help.

```
(1/4) Performing Source Validation
(1/4) Error during Source Validation, preliminary checks failed: Error while validating source: SERVER_ERROR - Cannot create PoolableConnectionFactory (FATAL: trust authentication failed for user "bowenwr")
Preliminary checks failed, aborting tests

[2017-09-20T09:28:02,682][INFO ][i.c.p.p.SslReqHandler    ] PSQL SSL support is disabled.
[2017-09-20T09:28:02,682][WARN ][i.c.p.p.Messages         ] trust authentication failed for user "zoomdata"
```

Please advise on how this should be fixed in the Dockerfile conf or instructions.

**Comment by christianbader** [comment]
@bowenwr as you mentioned above, it used the local user by default. 
Please use the user "crate" instead.

**Comment by awhipp** [comment]
@bowenwr @christianbader forking the PR and I'll take a look tomorrow morning

**Comment by awhipp** [comment]
@bowenwr I confirmed that the PR tests run successfully to the same fidelity as before the PR.

@christianbader I submitted a PR to your branch with some minor documentation updates indicating the crate user requirement. Once that is merged we can go ahead and merge your branch into this one.

**Comment by christianbader** [comment]
@awhipp thank you for testing and submitting the PR. Added just a minor comment.

**Comment by awhipp** [comment]
@christianbader I committed the change. Once you merge the wording into your branch we can accept the PR into this one. Thanks!

**Comment by christianbader** [comment]
@awhipp just merged and rebased the branch.

**Pull request merged**
